### ISSUE TITLE
Improve Comp Plugin

### ISSUE THREAD

**Issue by Setsugennoao** [Jaded-Encoding-Thaumaturgy/vs-preview#89]
- [x] Search range
- [x] Select index for base index of searching
    - [x] ALL
    - [x] 0-1-2...
    Explanation: for comping multiple sources, when searching for example P/B frames, you want to lookup pros of all. when doing it on filtered clip, you want to check the prop only on the source
    EDIT: made it so it's getting selected by the current clip
- [x] Bright/Dark frames selection (From #38)
    - [x] GUI Part
    - [x] Select index as before, so you can only check 
    EDIT: made it so it's getting selected by the current clipone source and not waste time
- [x] Checkbox for adding information in the top-left
  - Frame Type
  - Frame Number
  - Name
- [x] Option in the settings to add a minimum length between any sample frame (From #39)
- [x] Add hotkey for inputting current frame into manual frames textbox (From #75)
- [x] Add possibility of creating a random seed for comps, to make them reproducible (From #53)
- [x] Add manual frames parsing for automatically importing frames from scening toolbar (From #46)
- [x] Add ability to respect timestamps instead of frame numbers

For most of these items, we should also add stuff to #27

**Comment by LightArrowsEXE** [comment]
When creating a comparison, it only look at frame numbers. It should respect timestamps instead, like vspreview does regularly when syncing output clips. This should allow for clips with different framerates (including VFR) to be compared more consistently.

**Comment by Setsugennoao** [comment]
> When creating a comparison, it only looks at frame numbers. It should respect timestamps instead, like vspreview does regularly when syncing output clips. This should allow for clips with different framerates (including VFR) to be compared more consistently.

For the record, this got implemented.
